### ISSUE TITLE
ars-grin scrape fails on network outage

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/samara#31]
In recent grin scrape (see https://build.berkeleybop.org/job/extract-grin-traits/20), a (temporary?) network outage caused the scrape to be halted after generating 1.3 GB of trait data after running for 1 day and 18 hours. 

@cmungall was this a planned outage on bbop's jenkins ? 

@austinmeier Let me know if you think this is a reason to implement some more retry mechanisms to be a little more resilient against intermittent network outages.

```
[https://npgsweb.ars-grin.gov/gringlobal/methodaccession.aspx?id1=51081&id2=494186] downloaded.
[https://npgsweb.ars-grin.gov/gringlobal/methodaccession.aspx?id1=51081&id2=11002] downloading ...
Exception in thread "main" java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:512)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:493)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:205)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:194)
	at org.planteome.samara.ResourceUtil$class.get(ResourceUtil.scala:15)
	at org.planteome.samara.ScraperGrin$.get(ScraperGrin.scala:6)
	at org.planteome.samara.ScraperGrin$$anonfun$getAccessionIds$1$$anonfun$apply$7$$anonfun$apply$8.apply(ScraperGrin.scala:51)
	at org.planteome.samara.ScraperGrin$$anonfun$getAccessionIds$1$$anonfun$apply$7$$anonfun$apply$8.apply(ScraperGrin.scala:50)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at org.planteome.samara.ScraperGrin$$anonfun$getAccessionIds$1$$anonfun$apply$7.apply(ScraperGrin.scala:50)
	at org.planteome.samara.ScraperGrin$$anonfun$getAccessionIds$1$$anonfun$apply$7.apply(ScraperGrin.scala:47)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at org.planteome.samara.ScraperGrin$$anonfun$getAccessionIds$1.apply(ScraperGrin.scala:47)
	at org.planteome.samara.ScraperGrin$$anonfun$getAccessionIds$1.apply(ScraperGrin.scala:44)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at org.planteome.samara.ScraperGrin$.getAccessionIds(ScraperGrin.scala:44)
	at org.planteome.samara.ScraperGrin$$anonfun$scrape$1.apply(ScraperGrin.scala:14)
	at org.planteome.samara.ScraperGrin$$anonfun$scrape$1.apply(ScraperGrin.scala:13)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.planteome.samara.ScraperGrin$.scrape(ScraperGrin.scala:13)
	at org.planteome.samara.Samara$.delayedEndpoint$org$planteome$samara$Samara$1(Samara.scala:41)
	at org.planteome.samara.Samara$delayedInit$body.apply(Samara.scala:6)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at org.planteome.samara.Samara$.main(Samara.scala:6)
	at org.planteome.samara.Samara.main(Samara.scala)
Build step 'Execute shell' marked build as failure
```

**Comment by cmungall** [comment]
Sorry known outage at LBL

I can start again later or @kltm can do

@elserj any chance of an amazon instance or Osu machine we can slave to
Jenkins for this?

**Comment by austinmeier** [comment]
I don't believe this is a cause for concern, as I don't think we will need to run samara frequently.  The information on APS is not updated often.  I don't know how frequently the data is updated/added to GRIN.

**Comment by jhpoelen** [comment]
@cmungall @autinmeier thanks for comments. Sounds like this was an expected outage and there's no need to any additional network exception handling features.

**Comment by jhpoelen** [comment]
Just realized that the ars-grin scrape is on a weekly schedule (see https://build.berkeleybop.org/job/extract-grin-traits/). With limited information present, it appears that only 1 out of 10 scrapes completes without a socket error. Assuming that scheduled outages do not happen that often, I am re-opening this issue and figure out a way to stabilize the scraping process. If you have any major concerns about this, please do holler.

**Comment by jhpoelen** [comment]
I've added some simplistic way to make the scrape process a little more resilient. Rather than stopping the scrape on a network interruption, an error is logged and the scrape continues. Will wait until bbop jenkins incorporates these changes.

**Comment by jhpoelen** [comment]
GRIN scrape succeeded on https://build.berkeleybop.org/job/extract-grin-traits/25/ . There were some network errors (to be reported elsewhere if needed), but the scrape succeeded. Closing issue.

**Comment by cmungall** [comment]
great

FYI just give us a shout if you would like the resulting TSV pushed out to S3/CloudFront, rather than served off of the Jenkins machines.
