### ISSUE TITLE
grin scraper fails on parsing descriptordetails page 

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/samara#34]
For some reason, descriptor detail 310094 at https://npgsweb.ars-grin.gov/gringlobal/descriptordetail.aspx?id=310094 displays an error page. This causes the grin parser to misbehave.

From https://build.berkeleybop.org/job/extract-grin-traits/27/console :
```
[https://npgsweb.ars-grin.gov/gringlobal/descriptordetail.aspx?id=310094] downloading ...
[https://npgsweb.ars-grin.gov/gringlobal/descriptordetail.aspx?id=310094] downloaded.
Exception in thread "main" java.util.NoSuchElementException
	at java.util.ArrayList$Itr.next(ArrayList.java:854)
	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:40)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:448)
	at scala.collection.IterableLike.head(IterableLike.scala:106)
	at scala.collection.IterableLike.head$(IterableLike.scala:105)
	at net.ruippeixotog.scalascraper.model.LazyElementQuery.head(ElementQuery.scala:40)
	at net.ruippeixotog.scalascraper.scraper.ContentExtractors$.$anonfun$element$1(HtmlExtractor.scala:84)
	at net.ruippeixotog.scalascraper.scraper.SimpleExtractor.extract(HtmlExtractor.scala:62)
	at net.ruippeixotog.scalascraper.dsl.ScrapingOps$ElementsScrapingOps.$anonfun$extract$1(ScrapingOps.scala:16)
	at scalaz.Monad.$anonfun$map$2(Monad.scala:14)
	at scalaz.IdInstances$$anon$1.point(Id.scala:20)
	at scalaz.Monad.$anonfun$map$1(Monad.scala:14)
	at scalaz.IdInstances$$anon$1.bind(Id.scala:22)
	at scalaz.Monad.map(Monad.scala:14)
	at scalaz.Monad.map$(Monad.scala:14)
	at scalaz.IdInstances$$anon$1.map(Id.scala:19)
	at scalaz.syntax.FunctorOps.map(FunctorSyntax.scala:10)
	at net.ruippeixotog.scalascraper.dsl.ScrapingOps$ElementsScrapingOps.extract(ScrapingOps.scala:16)
	at 
```

**Comment by jhpoelen** [comment]
Reproduced and fixed issue.
